### ISSUE TITLE
[BUG] Default Shared Memory (shm) Size Limited to 64MB in Containerd Containers

### ISSUE THREAD

**Issue by panoanx** [davidliyutong/cloud-platform-apiserver#20]
Hello,

I've observed a significant limitation in the default configuration of containerd that impacts various applications, particularly those requiring a substantial amount of shared memory. The default shared memory (shm) size for containers managed by containerd is set to only 64MB. This default setting can lead to unexpected behavior or performance issues for applications that rely on shared memory for inter-process communication or other purposes.

**Issue Description:**
- The default shared memory size allocated for containers in containerd is limited to 64MB.
- This limitation affects applications that require more shared memory for their operations. For example, database systems, in-memory caches, or applications performing complex calculations in shared memory.
- The issue arises because the default shm size is not sufficient for these applications, potentially leading to crashes, performance degradation, or failure to start.

**Expected Behavior:**
- A larger default shm size or a more straightforward way to configure the shm size on a per-container basis. This would accommodate applications with higher shared memory requirements without requiring significant custom configuration.

**Possible Solutions:**
- Specify the emptyDir mount location and sizeLimit
- Specify an empty mount volume

```yaml
spec:
  volumes:
    - name: dshm
      emptyDir:
        medium: Memory
        sizeLimit: "1Gi"
  containers:
    - name: mycontainer
      image: your_image_name
      volumeMounts:
        - name: dshm
          mountPath: /dev/shm
```
